'use strict'
const test=require('node:test')
const assert=require('node:assert/strict')
const fs=require('fs')
const path=require('path')

test('CLI identity is ephemeral and runtime does not create Contract profiles',()=>{
  const text=fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'),'utf8')
  assert.match(text,/crypto\.randomBytes\(32\)/)
  assert.match(text,/this\.seed\.fill\(0\)/)
  assert.doesNotMatch(text,/\.profiles/)
  assert.doesNotMatch(text,/writeFileSync|writeFile\(|appendFile/)
})

test('wire versions and fee policy are tied to the current Contract pool',()=>{
  const text=fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'),'utf8')
  assert.match(text,/type:'mining-presence'/)
  assert.match(text,/v:9/)
  assert.match(text,/type:'mining-local-share'/)
  assert.match(text,/v:10/)
  assert.match(text,/type:'mining-pool-share'/)
  assert.match(text,/v:12/)
  assert.match(text,/CONTRACT_VERSION = '0\.1\.3'/)
  assert.match(text,/POOL_ID = 'byze-main-p2pool-v1'/)
})

test('coordination fallback frames remain non-PoW compatibility traffic', () => {
  const text = fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'), 'utf8')
  assert.match(text, /COORDINATION_PROOF_MODE\s*=\s*'coordination-test-v1'/)
  assert.match(text, /frame\.packet\?\.proofMode===COORDINATION_PROOF_MODE/)
  assert.match(text, /compatIgnoredRemote\+\+/)
  assert.match(text, /compatIgnoredRemote\+\+/)
})

test('v0.1.2 coalesces duplicate RandomX work and de-duplicates in-flight share history', () => {
  const text = fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'), 'utf8')
  assert.match(text, /randomxVerifyInflight\s*=\s*new Map\(\)/)
  assert.match(text, /pendingLocalShareIds\s*=\s*new Set\(\)/)
  assert.match(text, /pendingPoolShareIds\s*=\s*new Set\(\)/)
  assert.match(text, /async verifyRandomxHash\(header80, expectedHash\)/)
  assert.match(text, /this\.pendingLocalShareIds\.has\(rawShareId\)/)
  assert.match(text, /this\.pendingPoolShareIds\.has\(id\)/)
  assert.equal((text.match(/this\.supervisor\.verify\(/g) || []).length, 1, 'all remote PoW verification must pass through the coalescer')
})

test('v0.1.3 defers transient chain-context gaps and authenticates startup history', () => {
  const text = fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'), 'utf8')
  assert.match(text, /PRE_PRESENCE_GRACE_MS\s*=\s*5_000/)
  assert.match(text, /queuePrePresence\(peerKey, frame\)/)
  assert.match(text, /drainPrePresence\(peerKey\)/)
  assert.match(text, /CONSENSUS_UNKNOWN_CACHE_MS\s*=\s*1_000/)
  assert.match(text, /DEFERRED_CONTEXT_TTL_MS\s*=\s*120_000/)
  assert.match(text, /deferContext\('pool'/)
  assert.match(text, /retryDeferredContext\(\)/)
  assert.match(text, /remotePending:pendingCtx/)
  assert.match(text, /deferredLocalShares\.size\|\|this\.deferredPoolShares\.size/)
  assert.match(text, /PPLNS chain-context synchronization is in progress/)
})

test('v0.1.7 keeps miner UX compact and removes estimate, fee-wallet and periodic height noise without changing consensus files', () => {
  const text = fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'), 'utf8')
  const ui = fs.readFileSync(path.join(__dirname,'..','src','console-ui.js'), 'utf8')
  assert.doesNotMatch(text, /currentRewardEstimate\(\)/)
  assert.match(text, /scanRewards\(\)/)
  assert.match(text, /getblockhash/)
  assert.match(text, /rewardCelebration/)
  assert.match(text, /setInterval\(\(\)=>this\.stats\(\),10_000\)/)
  assert.doesNotMatch(text, /log\('PoolShare publiée'/)
  assert.doesNotMatch(text, /log\('job RandomX'/)
  assert.match(ui, /BYZE_P2POOL_BANNER/)
  assert.match(ui, /RandomX/)
  assert.doesNotMatch(ui, /Est\. next reward/)
  assert.match(ui, /MINING_SUCCESS_BANNER/)
  assert.doesNotMatch(ui, /Gain si bloc|Gains de la session|temporaire|Frais vers|Fee wallet|Height #/)
})

test('v0.2.4 keeps coinbase-binding-v2 with global-epoch-v6 and managed native isolation before PPLNS',()=>{
  const main=fs.readFileSync(path.join(__dirname,'..','src','byze-p2pool.js'),'utf8')
  const rx=fs.readFileSync(path.join(__dirname,'..','src','mining','p2pool-randomx.js'),'utf8')
  const native=fs.readFileSync(path.join(__dirname,'..','src','mining','native-bridge.js'),'utf8')
  const managed=fs.readFileSync(path.join(__dirname,'..','src','mining','native-components.js'),'utf8')
  const builder=fs.readFileSync(path.join(__dirname,'..','tools','build-native-bundle.js'),'utf8')
  assert.match(main,/SECURITY_GENERATION = 'coinbase-binding-v2-global-epoch-v6'/)
  assert.match(main,/verifyShareCoinbaseBinding\(checked,options=\{\}\)/)
  assert.match(main,/const binding=await this\.verifyShareCoinbaseBinding\(checked\); if\(!binding\.ok\)return binding/)
  assert.match(main,/const binding=await this\.verifyShareCoinbaseBinding\(checked\); if\(!binding\.ok\)\{warn\('local share coinbase binding rejected'/)
  assert.match(main,/verifyCoinbaseBinding\(\{rpc:/)
  assert.match(rx,/RANDOMX_PROOF_MODE = 'byze-randomx-v2'/)
  assert.match(rx,/jobCommitmentHash/)
  assert.match(rx,/coinbaseNoWitnessHex/)
  assert.match(rx,/coinbaseMerkleBranch/)
  assert.match(native,/contract-direct-coinbase-v2/)
  assert.match(native,/coinbaseNoWitnessHex/)
  assert.match(builder,/copySourceTree/)
  assert.match(builder,/sourceFingerprint/)
  assert.match(managed,/byze-p2pool-miner/)
  assert.doesNotMatch(native,/homedir\(\).*byze-miner|ldev.*byze-miner|Downloads.*byze-miner|pathLookup/)
})
